<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
services:
  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./pages:/usr/share/nginx/html
    networks:
      - promannet
    restart: unless-stopped
    profiles: ["dev", "prod"]

networks:
  promannet:
=======
=======
>>>>>>> 7afed144 (update the auth.py in controllers and add more code in security.py)
=======
>>>>>>> 8c3ce8e1 (get the latest code)
services:
  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./pages:/usr/share/nginx/html
    networks:
      - promannet
    restart: unless-stopped
    profiles: ["dev", "prod"]

networks:
  promannet:
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 2f07d766 (update code in auth.py and security.py)
=======
>>>>>>> 7afed144 (update the auth.py in controllers and add more code in security.py)
=======
>>>>>>> 8c3ce8e1 (get the latest code)
    driver: bridge